
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: local-path #заменить под свой storageClass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
